import Header from "@/components/header/Header";
import "./globals.scss";
import { Inter } from "next/font/google";
import Providers from "@/utils/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Главная",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="ru">
			<body className={inter.className}>
				<Providers>
					<div className="site">
						<Header />
						<main>{children}</main>
					</div>
				</Providers>
			</body>
		</html>
	);
}
